import type { Metadata } from "next";
import localFont from "next/font/local";
import { Balsamiq_Sans } from "next/font/google"
import "./globals.css";
import { Header } from "@/components/shared/header";
import SmoothScroll from "@/utils/smooth-scroll"
import { Providers } from "@/components/helpers/providers";
import RequestDataContainer from "@/components/helpers/request-data-container";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const balsamiqSans = Balsamiq_Sans({
    subsets: ['latin'],
    display: 'swap',
    weight: ["400", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    

  return (
    <Providers>
        <html lang="en">
            <SmoothScroll>
                <body
                  className={`${balsamiqSans.className} antialiased`}
                >
                        <RequestDataContainer />
                      <div className="fixed opacity-[0.008] z-1 top-0 left-0 w-full h-full bg-[url('/static/img/sharp.png')] bg-no-repeat"></div>
                      <div className="relative overflow-hidden w-full z-2 h-[100vh]">
                          <Header />
                          {children}
                      </div>
                </body>
            </SmoothScroll>
        </html>
    </Providers>
  );
}
